//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_Test.Models
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.CodeAnalysis;
    using System.Xml.Serialization;

    public partial class Cust:IXmlSerializable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cust()
        {
            this.Custs1 = new HashSet<Cust>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }

 
        public string Cust_IdX { get; set; }

        public string Tel { get; set; }
        public string Job { get; set; }
        public string Contry { get; set; }
         
        public bool IsLock { get; set; }

        
        public Nullable<System.DateTime> Date1 { get; set; }

       
        public string Note { get; set; }

        
        public Nullable<long> User_Add { get; set; }

     
        public Nullable<System.DateTime> Date_Add { get; set; }

        
        public Nullable<long> User_Edit { get; set; }

    
        public Nullable<System.DateTime> Date_Edit { get; set; }

        
        public string Discriminator { get; set; }

      
        public Nullable<long> Cust_Srch_Id { get; set; }

        
        public string hijry { get; set; }

 
        public double Digit { get; set; }
  
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
      
        public virtual ICollection<Cust> Custs1 { get; set; }

     
        public virtual Cust Cust1 { get; set; }
    }
}
