//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estate
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Owner_Name { get; set; }
        public string Owner_Tel { get; set; }
        public string Agent { get; set; }
        public string Agent_Tel { get; set; }
        public string AddX { get; set; }
        public string City { get; set; }
        public string Live { get; set; }
        public string Mony { get; set; }
        public string Accont_No { get; set; }
        public string Date_First { get; set; }
        public string Date_Second { get; set; }
        public Nullable<int> AirCondition { get; set; }
        public string Water_No { get; set; }
        public Nullable<int> Water_Push { get; set; }
        public string Lift_Name { get; set; }
        public string Lift_Tel_Company { get; set; }
        public string Lift_Tel { get; set; }
        public Nullable<int> Lift_Time { get; set; }
        public string Lift_Start { get; set; }
        public string Lift_End { get; set; }
        public bool IsLock { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public string Note { get; set; }
        public Nullable<long> User_Add { get; set; }
        public Nullable<System.DateTime> Date_Add { get; set; }
        public Nullable<long> User_Edit { get; set; }
        public Nullable<System.DateTime> Date_Edit { get; set; }
        public string Agent_Id { get; set; }
        public string Add_mini { get; set; }
        public string hijry { get; set; }
        public double Digit { get; set; }
    }
}
